const GET_ALL_POKEMON_SUCCESS = "GET_ALL_POKEMON_SUCCESS",
  GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS",
  GET_POKEMON_FAIL = "GET_POKEMON_FAIL",
  SEARCH_POKEMON_SUCCESS = "SEARCH_POKEMON_SUCCESS",
  CLEAR_POKEMON = "CLEAR_POKEMON",
  ERROR = "ERROR",
  LOADING = "LOADING";

export {
  GET_ALL_POKEMON_SUCCESS,
  GET_POKEMON_SUCCESS,
  GET_POKEMON_FAIL,
  SEARCH_POKEMON_SUCCESS,
  CLEAR_POKEMON,
  ERROR,
  LOADING
};
